'use client';

import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from '@react-pdf/renderer';
import type { Project } from '@/types/project';
import type { OutOfScopeItem, ChangeRequestTotals } from '@/lib/export/pdf';

interface ChangeRequestPdfProps {
  project: Project;
  outOfScopeItems: OutOfScopeItem[];
  totals: ChangeRequestTotals;
  includeBranding: boolean;
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: '#1a1a1a',
  },
  header: {
    marginBottom: 24,
  },
  title: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 8,
    color: '#111827',
  },
  subtitle: {
    fontSize: 11,
    color: '#6b7280',
    marginBottom: 4,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    marginVertical: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
    paddingBottom: 6,
    marginBottom: 4,
    fontFamily: 'Helvetica-Bold',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingVertical: 6,
  },
  totalsRow: {
    flexDirection: 'row',
    borderTopWidth: 2,
    borderTopColor: '#374151',
    paddingTop: 8,
    marginTop: 4,
    fontFamily: 'Helvetica-Bold',
  },
  colIndex: {
    width: '8%',
  },
  colItem: {
    width: '52%',
  },
  colHours: {
    width: '20%',
    textAlign: 'right',
  },
  colCost: {
    width: '20%',
    textAlign: 'right',
  },
  signatureSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 48,
  },
  signatureBlock: {
    width: '45%',
  },
  signatureLabel: {
    fontSize: 10,
    marginBottom: 24,
    fontFamily: 'Helvetica-Bold',
  },
  signatureLine: {
    borderBottomWidth: 1,
    borderBottomColor: '#1a1a1a',
    marginBottom: 4,
  },
  signatureDate: {
    fontSize: 8,
    color: '#6b7280',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#9ca3af',
  },
});

export function ChangeRequestPdf({
  project,
  outOfScopeItems,
  totals,
  includeBranding,
}: ChangeRequestPdfProps) {
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>CHANGE REQUEST</Text>
          <Text style={styles.subtitle}>Project: {project.name}</Text>
          <Text style={styles.subtitle}>Client: {project.clientName}</Text>
          <Text style={styles.subtitle}>Date: {today}</Text>
        </View>

        <View style={styles.divider} />

        {/* Table Header */}
        <View style={styles.tableHeader}>
          <Text style={styles.colIndex}>#</Text>
          <Text style={styles.colItem}>Item</Text>
          <Text style={styles.colHours}>Hours</Text>
          <Text style={styles.colCost}>Cost ({project.currency})</Text>
        </View>

        {/* Table Rows */}
        {outOfScopeItems.map((item, index) => (
          <View key={index} style={styles.tableRow}>
            <Text style={styles.colIndex}>{index + 1}</Text>
            <Text style={styles.colItem}>{item.title}</Text>
            <Text style={styles.colHours}>{item.actualHours.toFixed(1)}</Text>
            <Text style={styles.colCost}>{item.cost.toFixed(2)}</Text>
          </View>
        ))}

        {/* Totals */}
        <View style={styles.totalsRow}>
          <Text style={styles.colIndex} />
          <Text style={styles.colItem}>Total</Text>
          <Text style={styles.colHours}>
            {totals.totalOutOfScopeHours.toFixed(1)}
          </Text>
          <Text style={styles.colCost}>
            {totals.totalAdditionalCost.toFixed(2)}
          </Text>
        </View>

        {/* Signature Section */}
        <View style={styles.signatureSection}>
          <View style={styles.signatureBlock}>
            <Text style={styles.signatureLabel}>Client Signature</Text>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureDate}>Date: _______________</Text>
          </View>
          <View style={styles.signatureBlock}>
            <Text style={styles.signatureLabel}>Provider Signature</Text>
            <View style={styles.signatureLine} />
            <Text style={styles.signatureDate}>Date: _______________</Text>
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text>
            Generated by Scope Creep Tracker
            {includeBranding ? ' | Powered by LuroWeb' : ''}
          </Text>
        </View>
      </Page>
    </Document>
  );
}
